### ISSUE TITLE
fix: separate server components and client components better

### ISSUE THREAD

**Issue by jellllly420** [pkuSoftwareTeamWaterProof/forwardingQuotationPlatformFront#9]
Current implementation involves some ugly hacks due to the classification of components in Next.js. For example, we simply comment these code https://github.com/pkuSoftwareTeamWaterProof/forwardingQuotationPlatformFront/blob/4bab5a9d1a75c40b73a96c7aa7816fb8ce6cfe29/src/app/(auth)/register/page.tsx#L11-L13 to meet the need of a client component while server components cannot use most hooks in React.

With more careful design we should be able to get rid of these hacks. However, I haven't figure out how to do that now.

**Comment by laolee010126** [comment]
you can seperate codes that need to use React hooks to client components, and insert these into server components.
For example

https://github.com/pkuSoftwareTeamWaterProof/forwardingQuotationPlatformFront/blob/4bab5a9d1a75c40b73a96c7aa7816fb8ce6cfe29/src/app/(auth)/register/page.tsx#L15-L95

In this Register page, you can first make Register page to server component(Remove 'use client'). And the codes that need hook logic(<form></form> section), make it to new client component,  inside client component you can have any hooks and handlers. Insert this client component into Register page.
